[pytest]
minversion = 9.0.2
addopts = -ra
# ayuda a dar mas info
testpaths = 
    test # carpeta  donde debe buscar los test
markers =
    yatzy: test puntuaje yatzy
    upper: test para categorias singulares ( ones,twos,threes,etc..)
    pairs: test para categorias pares
    straigths: test para categorias straigths
    fullhouse: test para categorias  fullhouse
# se uso markers personalizados para evitar errores y para posibles refactorizaciones futuras.

# ESTO SE USA DESPUES 